[package]
name = "git-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
thiserror = "1.0.63"
byteorder = "1.5.0"
clap = { version = "4.5.16", features = ["derive"] }
chrono = "0.4.38"
